# Site settings
title: Elena Stagg
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Elena Stagg
user_title: Software Engineer
email: elenagracestagg@hotmail.co.uk
twitter_username: elenastagg
github_username: elenastagg

exclude: ["package.json", "src", "node_modules"]
