# Site settings
title: Elena Stagg
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Elena Stagg
user_description: Hi. My name is Elena and I am a software engineer based in Manchester UK looking for a dev role. I have projects demonstrating both front-end and backend skills but I am most confident with front-end technologies like React, HTML & CSS. You can preview some of my projects and the technologies I used below.
user_job: I love learning and taking on challenges so mentorship and development opportunities are important to me in a role. I'm a team player and love working with a vibrant, sociable team but I'm also happy working autonomously - I'm an adventurer at heart (I spent the last year or so travelling the world) so a remote or part-remote opportunity appeals too.
user_about: I like to spend my days playing with code and making new projects but in my spare time I love learning spanish, hiking/going on adventures, yoga, watching films, plus I really enjoy cooking for people so I love any excuse for a party!
user_title: Software Engineer
email: elenagracestagg@hotmail.co.uk
twitter_username: elenastagg
github_username: elenastagg

exclude: ["package.json", "src", "node_modules"]
